//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Controllers.Home {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Controllers.Home.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 意外错误！ 的本地化字符串。
        /// </summary>
        public static string Ajax_Error {
            get {
                return ResourceManager.GetString("Ajax_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 归档 的本地化字符串。
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论回复通知 的本地化字符串。
        /// </summary>
        public static string CommentReplyEmail {
            get {
                return ResourceManager.GetString("CommentReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 或者继续提交。 的本地化字符串。
        /// </summary>
        public static string ContinueSubmit {
            get {
                return ResourceManager.GetString("ContinueSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日 的本地化字符串。
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交失败，转载网站配置Content不能为空。 的本地化字符串。
        /// </summary>
        public static string Error_Tip1 {
            get {
                return ResourceManager.GetString("Error_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交失败，未能正确采集到数据。 的本地化字符串。
        /// </summary>
        public static string Error_Tip2 {
            get {
                return ResourceManager.GetString("Error_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交失败，暂时不支持该页面Url提交。 的本地化字符串。
        /// </summary>
        public static string Error_Tip3 {
            get {
                return ResourceManager.GetString("Error_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转到首页 的本地化字符串。
        /// </summary>
        public static string GoToHome {
            get {
                return ResourceManager.GetString("GoToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最新评论 的本地化字符串。
        /// </summary>
        public static string LatestComments {
            get {
                return ResourceManager.GetString("LatestComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败！格式不符合要求。 的本地化字符串。
        /// </summary>
        public static string ModificationFailed {
            get {
                return ResourceManager.GetString("ModificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功！ 的本地化字符串。
        /// </summary>
        public static string ModifiedSuccessfully {
            get {
                return ResourceManager.GetString("ModifiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败！ 的本地化字符串。
        /// </summary>
        public static string ModifyFailed {
            get {
                return ResourceManager.GetString("ModifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月 的本地化字符串。
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一篇 的本地化字符串。
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个相册 的本地化字符串。
        /// </summary>
        public static string NextAlbum {
            get {
                return ResourceManager.GetString("NextAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 留言回复通知 的本地化字符串。
        /// </summary>
        public static string NoteReplyEmail {
            get {
                return ResourceManager.GetString("NoteReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原文链接 的本地化字符串。
        /// </summary>
        public static string OriginalLink {
            get {
                return ResourceManager.GetString("OriginalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一篇 的本地化字符串。
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一个相册 的本地化字符串。
        /// </summary>
        public static string PreviousAlbum {
            get {
                return ResourceManager.GetString("PreviousAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索关键字 的本地化字符串。
        /// </summary>
        public static string SearchKey {
            get {
                return ResourceManager.GetString("SearchKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交成功，你可以 的本地化字符串。
        /// </summary>
        public static string SubmitSuccessfully {
            get {
                return ResourceManager.GetString("SubmitSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签 的本地化字符串。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string UrlPath {
            get {
                return ResourceManager.GetString("UrlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看文章 的本地化字符串。
        /// </summary>
        public static string ViewPost {
            get {
                return ResourceManager.GetString("ViewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你已经投过票！ 的本地化字符串。
        /// </summary>
        public static string Vote_Tip1 {
            get {
                return ResourceManager.GetString("Vote_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请您做出评价！ 的本地化字符串。
        /// </summary>
        public static string Vote_Tip2 {
            get {
                return ResourceManager.GetString("Vote_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谢谢您的参与！ 的本地化字符串。
        /// </summary>
        public static string Vote_Tip3 {
            get {
                return ResourceManager.GetString("Vote_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年 的本地化字符串。
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
