//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Models.Records {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Records {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Records() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Models.Records.Records", typeof(Records).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 回复后状态 的本地化字符串。
        /// </summary>
        public static string AssignStateID {
            get {
                return ResourceManager.GetString("AssignStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接受人或部门 的本地化字符串。
        /// </summary>
        public static string AssignTo {
            get {
                return ResourceManager.GetString("AssignTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接受对象ID 的本地化字符串。
        /// </summary>
        public static string AssignToObjectID {
            get {
                return ResourceManager.GetString("AssignToObjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配类型 的本地化字符串。
        /// </summary>
        public static string AssignType {
            get {
                return ResourceManager.GetString("AssignType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理意见 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复人 的本地化字符串。
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复时间 的本地化字符串。
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问题ID 的本地化字符串。
        /// </summary>
        public static string ProblemID {
            get {
                return ResourceManager.GetString("ProblemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复ID 的本地化字符串。
        /// </summary>
        public static string RecordID {
            get {
                return ResourceManager.GetString("RecordID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原状态 的本地化字符串。
        /// </summary>
        public static string SrcStateID {
            get {
                return ResourceManager.GetString("SrcStateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原用户 的本地化字符串。
        /// </summary>
        public static string SrcUserID {
            get {
                return ResourceManager.GetString("SrcUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态ID 的本地化字符串。
        /// </summary>
        public static string StateID {
            get {
                return ResourceManager.GetString("StateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
