//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Models.Category {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Category {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Category() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Models.Category.Category", typeof(Category).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 分类名称 的本地化字符串。
        /// </summary>
        public static string CateName {
            get {
                return ResourceManager.GetString("CateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义视图 的本地化字符串。
        /// </summary>
        public static string CustomView {
            get {
                return ResourceManager.GetString("CustomView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否显示在首页 的本地化字符串。
        /// </summary>
        public static string IsIndex {
            get {
                return ResourceManager.GetString("IsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否显示在导航 的本地化字符串。
        /// </summary>
        public static string IsNav {
            get {
                return ResourceManager.GetString("IsNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页显示记录条数 的本地化字符串。
        /// </summary>
        public static string ListNum {
            get {
                return ResourceManager.GetString("ListNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须为数字 的本地化字符串。
        /// </summary>
        public static string ListNum_Reg_Msg {
            get {
                return ResourceManager.GetString("ListNum_Reg_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父节点 的本地化字符串。
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 别名 的本地化字符串。
        /// </summary>
        public static string ReName {
            get {
                return ResourceManager.GetString("ReName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式要求：大小写字母开头，允许3-19字节，允许字母数字中，下划线 的本地化字符串。
        /// </summary>
        public static string ReName_Reg_Msg {
            get {
                return ResourceManager.GetString("ReName_Reg_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否可评论 的本地化字符串。
        /// </summary>
        public static string ReplyPermit {
            get {
                return ResourceManager.GetString("ReplyPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string UrlPath {
            get {
                return ResourceManager.GetString("UrlPath", resourceCulture);
            }
        }
    }
}
