//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Models.Web {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Web {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Web() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Models.Web.Web", typeof(Web).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱(eg: yqhomenet@gmail.com) 的本地化字符串。
        /// </summary>
        public static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Owen 的本地化字符串。
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文章列表分页记录数 的本地化字符串。
        /// </summary>
        public static string CatePagerCount {
            get {
                return ResourceManager.GetString("CatePagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论分页记录数 的本地化字符串。
        /// </summary>
        public static string CommentPagerCount {
            get {
                return ResourceManager.GetString("CommentPagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式错误 的本地化字符串。
        /// </summary>
        public static string Common_Reg_Msg {
            get {
                return ResourceManager.GetString("Common_Reg_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须项 的本地化字符串。
        /// </summary>
        public static string Common_Required_Msg {
            get {
                return ResourceManager.GetString("Common_Required_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文章转载目标分类Id集 例如.(1,2,3) 的本地化字符串。
        /// </summary>
        public static string ContributorCateIds {
            get {
                return ResourceManager.GetString("ContributorCateIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Powered by &lt;a href=&quot;http://www.yqhome.net/&quot; target=&quot;_blank&quot;&gt;Mvc3QA&lt;/a&gt; 的本地化字符串。
        /// </summary>
        public static string CopyRight {
            get {
                return ResourceManager.GetString("CopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插图总数 的本地化字符串。
        /// </summary>
        public static string DecorateImgCount {
            get {
                return ResourceManager.GetString("DecorateImgCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认语言 的本地化字符串。
        /// </summary>
        public static string DefaultLang {
            get {
                return ResourceManager.GetString("DefaultLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 女 的本地化字符串。
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备案号 的本地化字符串。
        /// </summary>
        public static string Icp {
            get {
                return ResourceManager.GetString("Icp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否发送回复提醒邮件 的本地化字符串。
        /// </summary>
        public static string IfSendReplyEmail {
            get {
                return ResourceManager.GetString("IfSendReplyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页分页记录数 的本地化字符串。
        /// </summary>
        public static string IndexPagerCount {
            get {
                return ResourceManager.GetString("IndexPagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 男 的本地化字符串。
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 截取为摘要信息的最大字符数 的本地化字符串。
        /// </summary>
        public static string MaxSummaryCount {
            get {
                return ResourceManager.GetString("MaxSummaryCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须为数字 的本地化字符串。
        /// </summary>
        public static string MustNum {
            get {
                return ResourceManager.GetString("MustNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 留言分页记录数 的本地化字符串。
        /// </summary>
        public static string NotePagerCount {
            get {
                return ResourceManager.GetString("NotePagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保密 的本地化字符串。
        /// </summary>
        public static string Secrecy {
            get {
                return ResourceManager.GetString("Secrecy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string SmtpPass {
            get {
                return ResourceManager.GetString("SmtpPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口(Gmail:587,Others:25) 的本地化字符串。
        /// </summary>
        public static string SmtpPort {
            get {
                return ResourceManager.GetString("SmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件服务器(eg: smtp.gmail.com) 的本地化字符串。
        /// </summary>
        public static string SmtpServer {
            get {
                return ResourceManager.GetString("SmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号(eg: yqhomenet) 的本地化字符串。
        /// </summary>
        public static string SmtpUser {
            get {
                return ResourceManager.GetString("SmtpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认风格 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式要求：eg. 200x150,90x60 的本地化字符串。
        /// </summary>
        public static string ThumbnailFormat {
            get {
                return ResourceManager.GetString("ThumbnailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相册缩略图设置 的本地化字符串。
        /// </summary>
        public static string ThumbnailInfo {
            get {
                return ResourceManager.GetString("ThumbnailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string UrlPath {
            get {
                return ResourceManager.GetString("UrlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站简介 的本地化字符串。
        /// </summary>
        public static string WebDescription {
            get {
                return ResourceManager.GetString("WebDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站点路径 的本地化字符串。
        /// </summary>
        public static string WebPath {
            get {
                return ResourceManager.GetString("WebPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站名称 的本地化字符串。
        /// </summary>
        public static string Webtitle {
            get {
                return ResourceManager.GetString("Webtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网站URL 的本地化字符串。
        /// </summary>
        public static string Weburl {
            get {
                return ResourceManager.GetString("Weburl", resourceCulture);
            }
        }
    }
}
