//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Admin {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Admin.Admin", typeof(Admin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增相册 的本地化字符串。
        /// </summary>
        public static string AddAlbum {
            get {
                return ResourceManager.GetString("AddAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增分类 的本地化字符串。
        /// </summary>
        public static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增内容 的本地化字符串。
        /// </summary>
        public static string AddContent {
            get {
                return ResourceManager.GetString("AddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        public static string Administrators {
            get {
                return ResourceManager.GetString("Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员列表 的本地化字符串。
        /// </summary>
        public static string Administratorslist {
            get {
                return ResourceManager.GetString("Administratorslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提交中... 的本地化字符串。
        /// </summary>
        public static string Ajax_Tip {
            get {
                return ResourceManager.GetString("Ajax_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相册 的本地化字符串。
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相册修改 的本地化字符串。
        /// </summary>
        public static string AlbumsEdits {
            get {
                return ResourceManager.GetString("AlbumsEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许评论 的本地化字符串。
        /// </summary>
        public static string AllowComments {
            get {
                return ResourceManager.GetString("AllowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文章 的本地化字符串。
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升序 的本地化字符串。
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示比例 的本地化字符串。
        /// </summary>
        public static string AspectRatio {
            get {
                return ResourceManager.GetString("AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础信息 的本地化字符串。
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础设置 的本地化字符串。
        /// </summary>
        public static string BasisSet {
            get {
                return ResourceManager.GetString("BasisSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面中调用 的本地化字符串。
        /// </summary>
        public static string Called {
            get {
                return ResourceManager.GetString("Called", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类 的本地化字符串。
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除当前分类及其子项？ 的本地化字符串。
        /// </summary>
        public static string CategoryDel_Tip {
            get {
                return ResourceManager.GetString("CategoryDel_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置分类信息 的本地化字符串。
        /// </summary>
        public static string CategoryReset {
            get {
                return ResourceManager.GetString("CategoryReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类设置 的本地化字符串。
        /// </summary>
        public static string CategorySettings {
            get {
                return ResourceManager.GetString("CategorySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 评论 的本地化字符串。
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置管理 的本地化字符串。
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定执行？ 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容列表 的本地化字符串。
        /// </summary>
        public static string ContentList {
            get {
                return ResourceManager.GetString("ContentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容管理 的本地化字符串。
        /// </summary>
        public static string ContentManagement {
            get {
                return ResourceManager.GetString("ContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 投稿 的本地化字符串。
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （单选按钮选中表示设为封面） 的本地化字符串。
        /// </summary>
        public static string Cover_Tip {
            get {
                return ResourceManager.GetString("Cover_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义区域[首页] 的本地化字符串。
        /// </summary>
        public static string CustomArea {
            get {
                return ResourceManager.GetString("CustomArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义区域[全网] 的本地化字符串。
        /// </summary>
        public static string CustomGlobalArea {
            get {
                return ResourceManager.GetString("CustomGlobalArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期 的本地化字符串。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除？ 的本地化字符串。
        /// </summary>
        public static string Delete_Tip {
            get {
                return ResourceManager.GetString("Delete_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除账号 的本地化字符串。
        /// </summary>
        public static string Deleteaccount {
            get {
                return ResourceManager.GetString("Deleteaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除选中项 的本地化字符串。
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除选中项？ 的本地化字符串。
        /// </summary>
        public static string DeleteSelected_Tip {
            get {
                return ResourceManager.GetString("DeleteSelected_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 降序 的本地化字符串。
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 草稿 的本地化字符串。
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件发送设置 的本地化字符串。
        /// </summary>
        public static string EmailSet {
            get {
                return ResourceManager.GetString("EmailSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 论坛配置 的本地化字符串。
        /// </summary>
        public static string ForumConfiguration {
            get {
                return ResourceManager.GetString("ForumConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID号 的本地化字符串。
        /// </summary>
        public static string IDnumber {
            get {
                return ResourceManager.GetString("IDnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即发布 的本地化字符串。
        /// </summary>
        public static string ImmediateRelease {
            get {
                return ResourceManager.GetString("ImmediateRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一次登录 的本地化字符串。
        /// </summary>
        public static string LastloginDate {
            get {
                return ResourceManager.GetString("LastloginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前位置 的本地化字符串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理首页 的本地化字符串。
        /// </summary>
        public static string ManagementHome {
            get {
                return ResourceManager.GetString("ManagementHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类手动管理 的本地化字符串。
        /// </summary>
        public static string ManualManagement {
            get {
                return ResourceManager.GetString("ManualManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 留言 的本地化字符串。
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改分类 的本地化字符串。
        /// </summary>
        public static string ModifyCategory {
            get {
                return ResourceManager.GetString("ModifyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改内容 的本地化字符串。
        /// </summary>
        public static string ModifyContent {
            get {
                return ResourceManager.GetString("ModifyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许评论 的本地化字符串。
        /// </summary>
        public static string NoComments {
            get {
                return ResourceManager.GetString("NoComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不推荐 的本地化字符串。
        /// </summary>
        public static string NoRecommended {
            get {
                return ResourceManager.GetString("NoRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不显示 的本地化字符串。
        /// </summary>
        public static string NoShow {
            get {
                return ResourceManager.GetString("NoShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不置顶 的本地化字符串。
        /// </summary>
        public static string NoSticky {
            get {
                return ResourceManager.GetString("NoSticky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Operating {
            get {
                return ResourceManager.GetString("Operating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帖子 的本地化字符串。
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        public static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐 的本地化字符串。
        /// </summary>
        public static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册日期 的本地化字符串。
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除管理 的本地化字符串。
        /// </summary>
        public static string Removetheadministrator {
            get {
                return ResourceManager.GetString("Removetheadministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转载配置 的本地化字符串。
        /// </summary>
        public static string ReproducedConfiguration {
            get {
                return ResourceManager.GetString("ReproducedConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存草稿 的本地化字符串。
        /// </summary>
        public static string SaveDraft {
            get {
                return ResourceManager.GetString("SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选取图片 的本地化字符串。
        /// </summary>
        public static string SelectPhotos {
            get {
                return ResourceManager.GetString("SelectPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SEO 的本地化字符串。
        /// </summary>
        public static string SEO {
            get {
                return ResourceManager.GetString("SEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设为管理 的本地化字符串。
        /// </summary>
        public static string Settoadministrator {
            get {
                return ResourceManager.GetString("Settoadministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单页 的本地化字符串。
        /// </summary>
        public static string SinglePage {
            get {
                return ResourceManager.GetString("SinglePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下子分类 的本地化字符串。
        /// </summary>
        public static string Subcategories {
            get {
                return ResourceManager.GetString("Subcategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功。 的本地化字符串。
        /// </summary>
        public static string Success_Tip {
            get {
                return ResourceManager.GetString("Success_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 置顶 的本地化字符串。
        /// </summary>
        public static string Top {
            get {
                return ResourceManager.GetString("Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有选取任何图片 的本地化字符串。
        /// </summary>
        public static string Upload_Tip {
            get {
                return ResourceManager.GetString("Upload_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分类用户界面管理 的本地化字符串。
        /// </summary>
        public static string UserInterface {
            get {
                return ResourceManager.GetString("UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户列表 的本地化字符串。
        /// </summary>
        public static string Userlist {
            get {
                return ResourceManager.GetString("Userlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册用户 的本地化字符串。
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
    }
}
