//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Views.Account {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Views.Account.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 帐户创建不成功。请更正错误并重试。 的本地化字符串。
        /// </summary>
        public static string Account_Error_Tip {
            get {
                return ResourceManager.GetString("Account_Error_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用以下表单创建新帐户。 的本地化字符串。
        /// </summary>
        public static string Account_Form_Tip {
            get {
                return ResourceManager.GetString("Account_Form_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帐户信息 的本地化字符串。
        /// </summary>
        public static string AccountInfo {
            get {
                return ResourceManager.GetString("AccountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本信息 的本地化字符串。
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改密码 的本地化字符串。
        /// </summary>
        public static string ChangePWD {
            get {
                return ResourceManager.GetString("ChangePWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录不成功。请更正错误并重试。 的本地化字符串。
        /// </summary>
        public static string Login_Error_Tip {
            get {
                return ResourceManager.GetString("Login_Error_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名和密码。如果您没有帐户，请 的本地化字符串。
        /// </summary>
        public static string Login_Tip {
            get {
                return ResourceManager.GetString("Login_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 资料修改 的本地化字符串。
        /// </summary>
        public static string ModifyInformation {
            get {
                return ResourceManager.GetString("ModifyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的评论 的本地化字符串。
        /// </summary>
        public static string MyComments {
            get {
                return ResourceManager.GetString("MyComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的留言 的本地化字符串。
        /// </summary>
        public static string MyMessages {
            get {
                return ResourceManager.GetString("MyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新帐户 的本地化字符串。
        /// </summary>
        public static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码更改不成功。请更正错误并重试。 的本地化字符串。
        /// </summary>
        public static string PWD_Error_Tip {
            get {
                return ResourceManager.GetString("PWD_Error_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请使用以下表单更改密码。 的本地化字符串。
        /// </summary>
        public static string PWD_Form_Tip {
            get {
                return ResourceManager.GetString("PWD_Form_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码必须至少包含 的本地化字符串。
        /// </summary>
        public static string PWD_Length_Tip1 {
            get {
                return ResourceManager.GetString("PWD_Length_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个字符。 的本地化字符串。
        /// </summary>
        public static string PWD_Length_Tip2 {
            get {
                return ResourceManager.GetString("PWD_Length_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的密码已成功更改。 的本地化字符串。
        /// </summary>
        public static string PWD_Success_Tip {
            get {
                return ResourceManager.GetString("PWD_Success_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传头像 的本地化字符串。
        /// </summary>
        public static string UploadAvatar {
            get {
                return ResourceManager.GetString("UploadAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string UrlPath {
            get {
                return ResourceManager.GetString("UrlPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息 的本地化字符串。
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
    }
}
