//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Controllers.Account {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Account {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Account() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Controllers.Account.Account", typeof(Account).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 提供的用户名或密码不正确。 的本地化字符串。
        /// </summary>
        public static string Account_Tip1 {
            get {
                return ResourceManager.GetString("Account_Tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份验证提供程序返回了错误。请验证您的输入并重试。如果问题仍然存在，请与系统管理员联系。  的本地化字符串。
        /// </summary>
        public static string Account_Tip10 {
            get {
                return ResourceManager.GetString("Account_Tip10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消用户创建请求。请验证您的输入并重试。如果问题仍然存在，请与系统管理员联系。 的本地化字符串。
        /// </summary>
        public static string Account_Tip11 {
            get {
                return ResourceManager.GetString("Account_Tip11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发生未知错误。请验证您的输入并重试。如果问题仍然存在，请与系统管理员联系。 的本地化字符串。
        /// </summary>
        public static string Account_Tip12 {
            get {
                return ResourceManager.GetString("Account_Tip12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前密码不正确或新密码无效。  的本地化字符串。
        /// </summary>
        public static string Account_Tip2 {
            get {
                return ResourceManager.GetString("Account_Tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名已存在。请输入不同的用户名。 的本地化字符串。
        /// </summary>
        public static string Account_Tip3 {
            get {
                return ResourceManager.GetString("Account_Tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该电子邮件地址的用户名已存在。请输入不同的电子邮件地址。 的本地化字符串。
        /// </summary>
        public static string Account_Tip4 {
            get {
                return ResourceManager.GetString("Account_Tip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供的密码无效。请输入有效的密码值。  的本地化字符串。
        /// </summary>
        public static string Account_Tip5 {
            get {
                return ResourceManager.GetString("Account_Tip5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供的电子邮件地址无效。请检查该值并重试。 的本地化字符串。
        /// </summary>
        public static string Account_Tip6 {
            get {
                return ResourceManager.GetString("Account_Tip6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供的密码取回答案无效。请检查该值并重试。 的本地化字符串。
        /// </summary>
        public static string Account_Tip7 {
            get {
                return ResourceManager.GetString("Account_Tip7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供的密码取回问题无效。请检查该值并重试。 的本地化字符串。
        /// </summary>
        public static string Account_Tip8 {
            get {
                return ResourceManager.GetString("Account_Tip8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提供的用户名无效。请检查该值并重试。  的本地化字符串。
        /// </summary>
        public static string Account_Tip9 {
            get {
                return ResourceManager.GetString("Account_Tip9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改密码 的本地化字符串。
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败！格式不符合要求。 的本地化字符串。
        /// </summary>
        public static string ModificationFailed {
            get {
                return ResourceManager.GetString("ModificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功！ 的本地化字符串。
        /// </summary>
        public static string ModifiedSuccessfully {
            get {
                return ResourceManager.GetString("ModifiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败！ 的本地化字符串。
        /// </summary>
        public static string ModifyFailed {
            get {
                return ResourceManager.GetString("ModifyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作失败 的本地化字符串。
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作成功 的本地化字符串。
        /// </summary>
        public static string OperationSuccessful {
            get {
                return ResourceManager.GetString("OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string UrlPath {
            get {
                return ResourceManager.GetString("UrlPath", resourceCulture);
            }
        }
    }
}
